
[workspace]
members = [
    "actix-gcd",
    "initial",
    "mandelbrot",
    "quickreplace",
    "fundamental-types",
    "ownership_and_moves",
    "references",
    "expressions",
    "error_handling",
    "ranges"
]
